<script setup lang="ts">
import { computed, ref } from 'vue'
import { BENIN_JOBS } from '../../benin/economy.ts'
import { loadBeninSave, newSave, saveBeninGame, money, workDay } from '../../benin/economy.ts'
const save=ref(loadBeninSave()??newSave()); const selected=ref(BENIN_JOBS[0]!); const saved=computed(()=>save.value.updatedAt)
function apply(){save.value.job={id:selected.value.id,title:selected.value.title};saveBeninGame(save.value)}
function work(){save.value=workDay(save.value,selected.value)}
</script>
<template><div class="life"><header><div><b>BENIN LIFE</b><span>Wallet & Career</span></div><strong>{{money(save.wallet.balance)}}</strong></header><section class="card"><h1>Live your life</h1><p>Choose a job, work a shift and earn Nigerian Naira.</p><div class="jobs"><button v-for="job in BENIN_JOBS" :key="job.id" :class="{on:selected.id===job.id}" @click="selected=job"><b>{{job.title}}</b><span>{{job.area}} · {{money(job.salary)}} / shift</span></button></div><div class="row"><button @click="apply">Apply / equip job</button><button @click="work">Work shift +{{money(selected.salary)}}</button></div></section><section class="card"><h2>Current life</h2><p>Job: {{save.job.title??'Unemployed'}}</p><p>Home: {{save.home.tier}} · {{save.home.area}}</p><small>Saved {{saved}}</small></section></div></template>
<style scoped>.life{min-height:100dvh;background:#11131a;color:#f7f4ed;padding:18px;max-width:760px;margin:auto;font-family:Inter,system-ui,sans-serif}.life header{display:flex;justify-content:space-between;align-items:center;padding:10px 0 18px}.life header b{display:block;letter-spacing:.14em}.life header span{font-size:12px;color:#a9b0bf}.card{background:#1a1e27;border:1px solid #343b48;border-radius:18px;padding:16px;margin-bottom:12px}.card p{color:#b9c0cc;line-height:1.5}.jobs{display:grid;gap:8px}.jobs button{display:flex;justify-content:space-between;gap:12px;text-align:left;background:#141820;color:#fff;border:1px solid #343b48;border-radius:12px;padding:12px}.jobs button span{color:#a9b0bf}.jobs button.on{border-color:#ffb020}.row{display:flex;gap:8px;margin-top:12px;flex-wrap:wrap}.row button{background:#ffb020;color:#211703;border:0;border-radius:12px;padding:11px 14px;font-weight:700}</style>