<script setup lang="ts">
import { computed, ref } from 'vue'
import { BENIN_AREAS, BENIN_CITY, BENIN_LOCATIONS, BENIN_ROADS, categoryLabel } from '../../benin/data.ts'
import { loadBeninSave, newSave, saveBeninGame, money } from '../../benin/economy.ts'
const query=ref(''); const selectedArea=ref<string|null>(null); const selectedLocation=ref(BENIN_LOCATIONS.find(x=>x.id==='kings-square')??null); const save=ref(loadBeninSave()??newSave())
const minLat=BENIN_CITY.bounds.south,maxLat=BENIN_CITY.bounds.north,minLon=BENIN_CITY.bounds.west,maxLon=BENIN_CITY.bounds.east
const x=(lon:number)=>8+((lon-minLon)/(maxLon-minLon))*84; const y=(lat:number)=>92-((lat-minLat)/(maxLat-minLat))*84
const roadPath=(points:[number,number][])=>points.map(([lat,lon],i)=>(i?'L':'M')+' '+x(lon).toFixed(2)+' '+y(lat).toFixed(2)).join(' ')
const filteredLocations=computed(()=>BENIN_LOCATIONS.filter(p=>{const q=query.value.trim().toLowerCase();return(!selectedArea.value||p.area===selectedArea.value)&&(!q||(`${p.name} ${p.area} ${p.road??''} ${categoryLabel(p.category)}`).toLowerCase().includes(q))}))
const areaName=computed(()=>selectedArea.value?(BENIN_AREAS.find(a=>a.id===selectedArea.value)?.name??'Benin City'):'Benin City')
function selectArea(id:string){selectedArea.value=id;const first=BENIN_LOCATIONS.find(p=>p.area===id);if(first)selectedLocation.value=first}
function saveNow(){saveBeninGame(save.value)} function reset(){save.value=newSave();saveNow()}
</script>
<template>
<div class="benin-map">
<header class="hud"><div><b>BENIN LIFE</b><span>Benin City · Edo State</span></div><div class="wallet">{{ money(save.wallet.balance) }}</div></header>
<div class="search"><input v-model="query" placeholder="Search Benin City: GRA, Ring Road, hotel, hospital…"/><button @click="selectedArea=null">City</button></div>
<main class="map-shell">
<svg viewBox="0 0 100 100" class="city-map" aria-label="Benin City road map"><rect width="100" height="100" rx="5" class="land"/>
<path v-for="road in BENIN_ROADS" :key="road.id" :d="roadPath(road.points)" :class="['road',{major:road.major}]"/>
<g v-for="area in BENIN_AREAS" :key="area.id" class="area" @click="selectArea(area.id)"><circle :cx="x(area.lon)" :cy="y(area.lat)" r="1.2"/><text :x="x(area.lon)+1.5" :y="y(area.lat)-1">{{ area.name }}</text></g>
<g v-for="place in filteredLocations" :key="place.id" class="poi" @click="selectedLocation=place"><circle :cx="x(place.lon)" :cy="y(place.lat)" r="1.5"/><text :x="x(place.lon)+1.7" :y="y(place.lat)+.5">{{ place.name }}</text></g>
</svg>
<aside class="panel"><div class="eyebrow">{{ areaName }}</div><h2>{{ selectedLocation?.name ?? 'Explore Benin City' }}</h2><p v-if="selectedLocation">{{ categoryLabel(selectedLocation.category) }} · {{ selectedLocation.road ?? selectedLocation.area }}<br/>Rating {{ selectedLocation.rating ?? '—' }} · {{ selectedLocation.playable ? 'Playable location' : 'Map location' }}</p><div class="actions"><button @click="saveNow">Save</button><button @click="reset">New life</button></div><div class="area-list"><button v-for="area in BENIN_AREAS" :key="area.id" :class="{on:selectedArea===area.id}" @click="selectArea(area.id)">{{ area.name }}</button></div></aside>
</main><footer class="mobile-nav"><button>City</button><button @click="saveNow">Save</button><button>Me</button><button>Life</button><button>Menu</button></footer>
</div></template>
<style scoped>.benin-map{height:100%;min-height:100dvh;background:#11131a;color:#f7f4ed;font-family:Inter,system-ui,sans-serif;overflow:hidden}.hud{height:68px;display:flex;align-items:center;justify-content:space-between;padding:10px 16px;background:rgba(15,17,24,.92);border-bottom:1px solid #2c303b}.hud b{display:block;letter-spacing:.14em}.hud span{font-size:12px;color:#a9b0bf}.wallet{font-weight:800}.search{position:absolute;z-index:4;top:78px;left:16px;right:16px;display:flex;gap:8px}.search input{flex:1;background:#171b24;border:1px solid #3a404d;color:white;border-radius:14px;padding:12px 14px;outline:none}.search button,.actions button,.area-list button,.mobile-nav button{border:1px solid #3a404d;background:#1b202a;color:#fff;border-radius:12px;padding:10px 12px}.map-shell{height:calc(100dvh - 68px);position:relative}.city-map{width:100%;height:100%;background:#171a20}.land{fill:#1b2028}.road{fill:none;stroke:#4b5260;stroke-width:.42;stroke-linecap:round;stroke-linejoin:round}.road.major{stroke:#a5adb9;stroke-width:.75}.area circle{fill:#ffb020}.area text,.poi text{font-size:1.5px;fill:#dfe4ec;pointer-events:none}.poi circle{fill:#ff5f56;stroke:#171a20;stroke-width:.45}.poi text{font-size:1.15px;fill:#fff}.panel{position:absolute;right:16px;top:84px;width:300px;max-height:calc(100% - 100px);overflow:auto;padding:16px;border:1px solid #343b48;border-radius:18px;background:rgba(18,21,29,.9);backdrop-filter:blur(12px)}.eyebrow{color:#ffb020;font-size:12px;text-transform:uppercase;letter-spacing:.1em}.panel h2{margin:6px 0}.panel p{color:#b9c0cc;font-size:13px;line-height:1.5}.actions{display:flex;gap:8px;margin:12px 0}.area-list{display:grid;grid-template-columns:1fr 1fr;gap:6px}.area-list button{font-size:11px;text-align:left}.area-list button.on{border-color:#ffb020;color:#ffb020}.mobile-nav{display:none}@media(max-width:720px){.panel{left:10px;right:10px;top:auto;bottom:64px;width:auto;max-height:34dvh}.area-list{display:none}.search{top:76px}.mobile-nav{position:absolute;z-index:6;display:grid;grid-template-columns:repeat(5,1fr);left:0;right:0;bottom:0;padding:5px;background:#11131a;border-top:1px solid #2c303b}.mobile-nav button{border:0;border-radius:10px;background:transparent;font-size:11px}.mobile-nav button:first-child{color:#ffb020}}</style>